force-app/main/default/objects/Open_Ai__c/Open_Ai__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Open AI</label>
</CustomObject>

force-app/main/default/objects/Open_Ai__c/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <label>Api_Key</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utils.cls
public with sharing class Utils {
    public static String getApiKey(){
       return Open_Ai__c.getInstance().Api_Key__c;
    }

    public static HttpResponse apiCaller(String endpoint, String body, String method){
        // Set HTTP Request
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setMethod(method);
        req.setHeader('Authorization','Bearer '+ getApiKey());
        req.setHeader('Content-Type', 'application/json; charset=UTF-8');
        if(body!=''){
            req.setBody(body);
        }
        
        req.setTimeout(120000);

        Http http = new Http();
        HttpResponse res = http.send(req);
        return res;
    }
}